name: scaffold_tab_bar_example
description: Demonstrates how to use the scaffold_tab_bar plugin.
publish_to: 'none'

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  scaffold_tab_bar: any

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  scaffold_tab_bar:
    git:
      url: https://github.com/AppleEducate/scaffold_tab_bar
      ref: web
